### ISSUE TITLE
Matrix key is not computed

### ISSUE THREAD

**Issue by getlarge** [cloudposse/github-action-matrix-outputs-write#19]
Hey, to start off i would like to thank you for this very useful action that saved my day!

## Describe the Bug

Maybe this is a desired behaviour but reading the README let me think that the `matrix-key` option would allow to compute a custom property name that would contain the `outputs` struct.
But after trying the action and reading this [line](https://github.com/cloudposse/github-action-matrix-outputs-write/blob/main/index.js#L65), `matrix_key` is just a plain string. Is it a mistake and that should have been `{ [matrix_key]: outputs_struct }` or is it intentional and i'm missing something ?

## Expected Behavior

I was expecting to define my own property names

## Workaround

Well, if we could skip using `matrix-key` and define the key in the outputs that would be fine, but currently it throws an error as matrix-key is required when `matrix-step-name` is defined.

## Steps to Reproduce

Here's a workflow extract:

```yaml
  deploy-in-parallel:
    needs: [init]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true

    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        # affected-apps is an array of strings
        app: ${{ fromJSON(needs.init.outputs.affected-apps) }}

    steps:
      - uses: actions/checkout@v3

      # workaround to output job status until https://github.com/actions/runner/pull/2477 is completed and deployed
      - name: Output job status in artifact
        if: always()
        id: out
        uses: cloudposse/github-action-matrix-outputs-write@main
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.app }}
          outputs: |-
            ${{ matrix.app }}: ${{ job.status }}
```

## Screenshots

Example artifact:
```json
{"matrix_key":{"my-service":"failure"}}
```

## Environment (please complete the following information):

Github actions runner - Ubuntu
